baseURL = "https://kairichardkoenig.de"
languageCode = "en-us"
title = "Kai Richard König"
themesDir = "themes"
theme = "hugo-whisper-theme"
enableInlineShortcodes = true
enableGitInfo = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableEmoji = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30
[related]
toLower = false
includeNewer = true
threshold = 80
  [[related.indices]]
  name = "keywords"
  weight = 100.0
  [[related.indices]]
  name = "date"
  weight = 10.0

[[menu.main]]
    name = "Profile"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3

[params]
  google_analytics_id=""
  homepage_button_link = '/about'
  homepage_button_text = 'More'
  homepage_intro = 'A generalist always searching for new oppertunities to grow.'
  homepage_image = '/images/terminal.gif'
  mainSections = ["blog", "about", "imprint"]

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Kai Richard König is generalist always searching for new opportunities to grow."
    meta_og_title = "Kai Richard König"
    meta_og_type = "website"
    meta_og_url = "https://kairichardkoenig.de"
    meta_og_description = "Kai Richard König is generalist always search for new oppertunities to grow."
    meta_twitter_card = "summary"
    meta_twitter_site = "@kai_richard"
    meta_twitter_creator = "@kai_richard"

  [params.logo]
      mobile = "/images/head_circle.png"
      standard  = "/images/head_circle.png"

[markup]
  [markup.highlight]
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "monokailight"
    tabWidth = 4

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "CatmullRom"

# Default JPEG quality setting. Default is 75.
quality = 100

# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
anchor = "smart"

# Default background color.
# Hugo will preserve transparency for target formats that supports it,
# but will fall back to this color for JPEG.
# Expects a standard HEX color string with 3 or 6 digits.
# See https://www.google.com/search?q=color+picker
bgColor = "#ffffff"
