baseURL = "https://kairichardkoenig.de"
languageCode = "en-us"
title = "Kai Richard König"
themesDir = "themes"
theme = "hugo-whisper-theme"
enableInlineShortcodes = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableEmoji = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30
[related]
toLower = false
includeNewer = true
threshold = 80
  [[related.indices]]
  name = "keywords"
  weight = 100.0
  [[related.indices]]
  name = "date"
  weight = 10.0

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3

[params]
  google_analytics_id=""
  homepage_button_link = '/about'
  homepage_button_text = 'More'
  homepage_intro = 'A generalist always searching for new oppertunities to grow.'
  homepage_image = '/images/terminal.gif'
  mainSections = ["blog", "about", "imprint"]

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Kai Richard König is generalist always searching for new opportunities to grow."
    meta_og_title = "Kai Richard König"
    meta_og_type = "website"
    meta_og_url = "https://kairichardkoenig.de"
    meta_og_description = "Kai Richard König is generalist always search for new oppertunities to grow."
    meta_twitter_card = "summary"
    meta_twitter_site = "@kai_richard"
    meta_twitter_creator = "@kai_richard"

  [params.logo]
      mobile = "/images/head_circle.png"
      standard  = "/images/head_circle.png"

[markup]
  [markup.highlight]
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "monokailight"
    tabWidth = 4