name: Continuous Integration
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.58.3"
          extended: true

      - name: Build
        run: hugo --gc --minify --i18n-warnings --log

      - name: Upload site
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download site
        uses: actions/download-artifact@v1
        with:
          name: site
      - name: deploy
        run: |
          npm i now 
          export export PATH=`npm bin path`:$PATH
          cd site/ && NOW_PROJECT_ID=${{ secrets.NOW_PROJECT_ID }} NOW_ORG_ID=${{ secrets.NOW_PROJECT_ID }} now --token=${{ secrets.NOW_TOKEN }} deploy --prod
