name: Continuous Integration
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.128.2"
          extended: true

      - name: Build
        run:  hugo --gc --minify --printI18nWarnings -v

      - name: Upload site
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: ./public

  verify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download site
        uses: actions/download-artifact@v1
        with:
          name: site

      - name: bork
        run: |
          curl -L https://github.com/smallhadroncollider/brok/releases/download/1.1.0/brok-1.1.0_x86-64-linux.tar.gz -o bork.tar.gz
          tar -xvzf bork.tar.gz
          ./brok --only-failures --ignore "https://t.co/DlOcGYdnwB" "https://kairichardkoenig.de" "https://www.linkedin.com" "https://easytainer.cloud" "http://161.111.111.111" "https://www.futurepackagingforum.com/" "https://linkist.de/" "https://dilbertblog.typepad.com" "https://www.hotcars.com/" $(find ./site -type f -name "*.html")

  deploy:
    environment:
      name: production
      url: https://kairichardkoenig.de
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4